# Generated by Django 2.0.5 on 2018-05-17 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bilet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poczatek_lotnisko', models.CharField(max_length=255)),
                ('koniec_lotnisko', models.CharField(max_length=255)),
                ('poczatek_czas', models.DateTimeField()),
                ('koniec_czas', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Pasazer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=30)),
                ('nazwisko', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Samolot',
            fields=[
                ('nr_rej', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('ile_miejsc', models.IntegerField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='pasazer',
            unique_together={('imie', 'nazwisko')},
        ),
        migrations.AddField(
            model_name='lot',
            name='samolot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linie_lotnicze.Samolot'),
        ),
        migrations.AddField(
            model_name='bilet',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linie_lotnicze.Lot'),
        ),
        migrations.AddField(
            model_name='bilet',
            name='pasazer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linie_lotnicze.Pasazer'),
        ),
    ]
