# Generated by Django 2.0.5 on 2018-06-13 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('linie_lotnicze', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zaloga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kapitanImie', models.CharField(max_length=30)),
                ('kapitanNazwisko', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='zaloga',
            unique_together={('kapitanImie', 'kapitanNazwisko')},
        ),
        migrations.AddField(
            model_name='lot',
            name='zaloga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='linie_lotnicze.Zaloga'),
        ),
    ]
